version: 2
registries:
  docker-gitlab:
    type: docker-registry
    url: registry.gitlab.com
    username: dependabot-bot
    password: ${{secrets.GITLAB_DOCKER_REGISTRY_TOKEN}}
  maven-gitlab:
    type: maven-repository
    url: https://gitlab.com/api/v4/projects/32058529/packages/maven
  maven-gitlab-no-base:
    type: maven-repository
    url: https://gitlab.com/api/v4/projects/32058529/packages/maven
    replaces-base: true
  npm-gitlab:
    type: npm-registry
    url: gitlab.com/api/v4/projects/32058529/packages/npm/
    token: ${{secrets.GITLAB_NPM_REGISTRY_TOKEN}}
  npm-gitlab-instance:
    type: npm-registry
    url: gitlab.com/api/v4/packages/npm
    token: ${{secrets.GITLAB_NPM_REGISTRY_TOKEN}}
  terraform-gitlab:
    type: terraform-registry
    url: gitlab.com
    token: ${{secrets.GITLAB_TF_REGISTRY_TOKEN}}
  python-gitlab:
    type: python-index
    url: https://gitlab.com/api/v4/projects/32058529/packages/pypi/simple
    username: dependabot-bot
    password: ${{secrets.GITLAB_PYPI_TOKEN}}
    replaces-base: false
updates:
  - package-ecosystem: gradle
    directory: "/java"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-type: all
    registries:
      - maven-mapbox
      - maven-gitlab
  - package-ecosystem: gradle
    directory: "/java_2"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-type: all
    registries:
      - maven-gitlab-no-base
  - package-ecosystem: pip
    directory: "/python"
    insecure-external-code-execution: allow
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries:
      - python-gitlab
  - package-ecosystem: bundler
    directory: "/ruby"
    vendor: true
    insecure-external-code-execution: allow
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries:
      - rubygems
  - package-ecosystem: bundler
    directory: "/ruby_2"
    insecure-external-code-execution: allow
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries:
      - rubygems
  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: daily
    registries:
      - docker-gitlab
  - package-ecosystem: npm
    directory: /npm
    schedule:
      interval: daily
    registries:
      - npm-gitlab
      - npm-gitlab-instance
  - package-ecosystem: npm
    directory: /pnpm
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /yarn
    schedule:
      interval: daily
  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: daily
    registries:
      - terraform-gitlab
  - package-ecosystem: gomod
    directory: /go
    schedule:
      interval: daily
    registries:
      - none
  - package-ecosystem: cargo
    directory: "/rust"
    schedule:
      interval: daily
